### ISSUE TITLE
[1.10.2] Some Flag error

### ISSUE THREAD

**Issue by mister-man** [FabioZumbi12/Sponge-Redprotect-19#5]
Hallo together,

I tried the flag system, but found serveral errors. If I set the flag "Spawn-Monsters" tp true, in my protectet area spawn moster. Further if I use the command, "/rp info", there is no way to show the flags for a region, like in worldguard.

Thanks a lot.

PS: Last version of Sponge and last version of rp

**Comment by FabioZumbi12** [comment]
Hello,

Use /rp flag info to see the flag properties of a Region.

**Comment by mister-man** [comment]
Okay thanks... It was not a bug, it was a misstake. all flags are working fine.

thanks... close
